// 此文件由 scripts/plugin-capabilities.mjs 生成，请勿手工修改。
pub(crate) const VALID_PERMISSIONS: &[&str] = &[
    "notes.read",
    "notes.write",
    "document.read",
    "document.write",
    "tasks.read",
    "tasks.write",
    "ai.invoke",
    "ai.context.read",
    "ai.context.augment",
    "ai.session.read",
    "ui.editor.toolbar",
    "ui.chat.toolbar",
    "ui.chat.panel",
    "planning.files.read",
    "planning.files.write",
    "network.request",
    "files.readSelected",
    "files.writeSelected",
    "prompts.register",
    "views.register",
    "mcp.connect",
    "credentials.use",
    "credentials.configure",
    "network.xingchen",
    "agents.invoke",
    "editor:read",
    "editor:write",
    "workspace:read",
    "workspace:write",
    "notes:read",
    "notes:write",
    "settings:read",
    "settings:write",
    "files:read",
    "files:write",
    "network:request",
    "clipboard:read",
    "clipboard:write",
    "tasks.subscribe",
    "taskViews.register",
    "ai:chat",
    "ai:models",
];

pub(crate) const V3_MANIFEST_PERMISSIONS: &[&str] = &[
    "document.read",
    "document.write",
    "tasks.read",
    "tasks.write",
    "ai.invoke",
    "ai.context.read",
    "ai.context.augment",
    "ai.session.read",
    "ui.editor.toolbar",
    "ui.chat.toolbar",
    "ui.chat.panel",
    "planning.files.read",
    "planning.files.write",
    "network.request",
    "files.writeSelected",
    "prompts.register",
    "mcp.connect",
    "credentials.use",
    "network.xingchen",
    "agents.invoke",
];

pub(crate) const V3_PERMISSION_RUNTIME_KINDS: &[(&str, &[&str])] = &[
    ("document.read", &["declarative-ui", "xingchen-agent", "xingchen-workflow"]),
    ("document.write", &["declarative-ui", "xingchen-agent", "xingchen-workflow"]),
    ("tasks.read", &["legacy-js"]),
    ("tasks.write", &["legacy-js"]),
    ("ai.invoke", &["declarative-ui", "xingchen-agent", "xingchen-workflow"]),
    ("ai.context.read", &["prompt-pack"]),
    ("ai.context.augment", &["prompt-pack", "declarative-ui", "xingchen-agent", "xingchen-workflow"]),
    ("ai.session.read", &["prompt-pack"]),
    ("ui.editor.toolbar", &["declarative-ui"]),
    ("ui.chat.toolbar", &["prompt-pack"]),
    ("ui.chat.panel", &["prompt-pack"]),
    ("planning.files.read", &["prompt-pack"]),
    ("planning.files.write", &["prompt-pack"]),
    ("network.request", &["xingchen-agent", "xingchen-workflow", "mcp-connector"]),
    ("files.writeSelected", &["xingchen-agent", "xingchen-workflow"]),
    ("prompts.register", &["prompt-pack"]),
    ("mcp.connect", &["mcp-connector"]),
    ("credentials.use", &["xingchen-agent", "xingchen-workflow", "mcp-connector"]),
    ("network.xingchen", &["xingchen-agent", "xingchen-workflow"]),
    ("agents.invoke", &["xingchen-agent", "xingchen-workflow"]),
];
