// GDS Graph Projections for Manufacturing
// Generated by create-context-graph
// Note: Requires Neo4j GDS plugin (AuraDS or Enterprise + GDS)

// Full entity projection (all node labels and relationship types)
CALL gds.graph.project(
  'manufacturing_full',
  ['Person', 'Organization', 'Location', 'Event', 'Object', 'Machine', 'Part', 'WorkOrder', 'Supplier', 'QualityReport', 'ProductionLine'],
  ['WORKS_FOR', 'LOCATED_AT', 'PARTICIPATED_IN', 'ASSEMBLED_FROM', 'SUPPLIED_BY', 'INSPECTED', 'PRODUCED_ON', 'DEPENDS_ON', 'OPERATED_BY', 'ASSIGNED_TO', 'REPORTED_BY']
);

// Community detection
CALL gds.louvain.write('manufacturing_full', {
  writeProperty: 'community'
});

// PageRank centrality
CALL gds.pageRank.write('manufacturing_full', {
  writeProperty: 'pagerank'
});

// FastRP embeddings for structural similarity
CALL gds.fastRP.write('manufacturing_full', {
  embeddingDimension: 128,
  writeProperty: 'fastrp_embedding'
});

// Clean up projection
CALL gds.graph.drop('manufacturing_full');
